### ISSUE TITLE
[视觉体验优化] 模组状态指示灯红绿色优化

### ISSUE THREAD

**Issue by Nelocompne** [auto-created-name/L4d2_Mod_Manager_Tool#1]
**[视觉体验优化] 模组状态指示灯红绿色优化**

使用版本：[V0.3.0 Dev1](https://github.com/auto-created-name/L4d2_Mod_Manager_Tool/releases/tag/0.3.0.dev1_build2207162132)
- 目前的状态指示灯对 _红绿色盲/色弱_ 用户并不是非常友好，希望改善为区别更为明显的颜色。

![image](https://user-images.githubusercontent.com/40271506/179726539-0f33c144-5043-48e3-ad5b-343774af0a78.png)

**Comment by auto-created-name** [comment]
好的，我修改下图标样式来区分，并且重新选择颜色试试

**Comment by auto-created-name** [comment]
模组状态指示灯的图标已经优化，查看发布[0.3.0 Dev3](https://github.com/auto-created-name/L4d2_Mod_Manager_Tool/releases/tag/0.3.0.dev3)

![捕获](https://user-images.githubusercontent.com/25795343/180594293-d4cad030-cbd2-4a24-b8c3-3373409ca880.PNG)

**Comment by Nelocompne** [comment]
感谢您的工作
