### ISSUE TITLE
[不是问题]阿巴巴巴，这个要怎么下载使用

### ISSUE THREAD

**Issue by alreShan** [auto-created-name/L4d2_Mod_Manager_Tool#6]
真的不会怎么下载来用，[README.md](https://github.com/auto-created-name/L4d2_Mod_Manager_Tool#readme)里面写的安装没有什么内容，看不明白。
不懂就问：这个要怎么用

**Comment by alreShan** [comment]
我只有在某个小网站上面找的0.3.0.a2版本，还是压缩包直接解压就可以用的，真的看不懂README.md里面写的安装方法

**Comment by alreShan** [comment]
求教 X(  ，l4d2游戏内自带的模组管理用起来太痛苦了。

**Comment by alreShan** [comment]
啊，原来是release的内容不显示而已，对不起

**Comment by auto-created-name** [comment]
Sorry今天才看到你的issue，你能自己搞定很棒哦你能自己搞定很棒哦
